# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: 2022 Andy Holmes <andrew.g.r.holmes@gmail.com>

name: Actuary
description: Build and host a Flatpak repository
author: Andy Holmes
branding:
  icon: package
  color: brown
inputs:
  suite:
    description: |
      The test suite to run.
    default: test
    required: false
  compiler:
    description: |
      The compiler suite to use.
    required: false

  setup-args:
    description: >
      Extra command-line options for `meson setup`.
    required: false

  # `test` Options
  test-args:
    description: >
      Extra command-line options for `meson test`.
    required: false
  test-coverage:
    description: >
      Enable or disable coverage generation.
    default: false
    required: false

  # `abidiff` Options
  abidiff-args:
    description: >
      Extra command-line options for `abidiff`.
    required: false
  abidiff-lib:
    description: >
      Library path, relative to `$LIBDIR`
    required: true

  # `cppcheck` Options
  cppcheck-args:
    description: >
      Extra command-line options for `cppcheck`.
    required: false
  cppcheck-path:
    description: >
      Path to the source directory.
    default: .
    required: false

  # LCOV Options
  lcov-include:
    description: >
      Path glob of directories to include in coverage.
    required: false
  lcov-exclude:
    description: >
      Path glob of directories to exclude from coverage.
    required: false

outputs:
  log:
    description: >
      Path to the primary log file for the suite.
  coverage:
    description: >
      Path to the coverage report.
  coverage-html:
    description: >
      Path to the coverage report (HTML).

runs:
  using: node20
  main: dist/index.js
