name: Continuous Integration

on:
  pull_request:

permissions:
  contents: read

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Spell Check
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: doubleclick,inout,onlyonce,sav
          skip: .git

  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint
        uses: wagoid/commitlint-github-action@v5

  reuse:
    name: REUSE Compliance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        uses: fsfe/reuse-action@v1
        with:
          args: lint
