name: Continuous Integration

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Initialize
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Build
        uses: github/codeql-action/autobuild@v3

      - name: Analyze
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"
        
  codespell:
    name: Codespell
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Spell Check
        uses: codespell-project/actions-codespell@master
        with:
          skip: .git,dist

  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Lint
        uses: wagoid/commitlint-github-action@v6

  reuse:
    name: REUSE Compliance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Lint
        uses: fsfe/reuse-action@v6
        with:
          args: lint

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: ShellCheck
        if: ${{ always() }}
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review
          fail_level: any
